#!/bin/sh
# Copyright (C) 2014 Torkild U. Resheim.

if [ "$SYNOPKG_PKG_STATUS" != "UPGRADE" ]; then
	/usr/syno/bin/servicetool --remove-configure-file --package Archiva.sc
	[ $? -ne 0 ] && echo "Failed to remove port of Archiva from firewall" > $SYNOPKG_TEMP_LOGFILE
fi

exit 0
