#!/bin/sh
# Copyright (C) 2000-2014 Synology Inc. All rights reserved.

LANG_FILE=`dirname $0`/lang/$SYNOPKG_DSM_LANGUAGE
if [ -f ${LANG_FILE} ]; then
	. ${LANG_FILE}
else
	. `dirname $0`/lang/default
fi
